var usa_regions = {	
	"Alaska":"West", 
	"Alabama":"South", 
	"Arkansas":"South", 
	"Arizona":"West", 
	"California":"West", 
	"Colorado":"West", 
	"Connecticut":"Northeast", 
	"District of Columbia":"South", 
	"Delaware":"South", 
	"Florida":"South", 
	"Georgia":"South", 
	"Hawaii":"West", 
	"Iowa":"Midwest", 
	"Idaho":"West", 
	"Illinois":"Midwest", 
	"Indiana":"Midwest", 
	"Kansas":"Midwest", 
	"Kentucky":"South", 
	"Louisiana":"South", 
	"Massachusetts":"Northeast", 
	"Maryland":"South", 
	"Maine":"Northeast", 
	"Michigan":"Midwest", 
	"Minnesota":"Midwest", 
	"Missouri":"Midwest", 
	"Mississippi":"South", 
	"Montana":"West", 
	"North Carolina":"South", 
	"North Dakota":"Midwest", 
	"Nebraska":"Midwest", 
	"New Hampshire":"Northeast", 
	"New Jersey":"Northeast", 
	"New Mexico":"West", 
	"Nevada":"West", 
	"New York":"Northeast", 
	"Ohio":"Midwest", 
	"Oklahoma":"South", 
	"Oregon":"West", 
	"Pennsylvania":"Northeast", 
	"Rhode Island":"Northeast", 
	"South Carolina":"South", 
	"South Dakota":"Midwest", 
	"Tennessee":"South", 
	"Texas":"South", 
	"Utah":"West", 
	"Virginia":"South", 
	"Vermont":"Northeast", 
	"Washington":"West", 
	"Wisconsin":"Midwest", 
	"West Virginia":"South", 
	"Wyoming":"West"
}

var europe_regions = {
	"Belarus":"East",
	"Bulgaria":"East",
	"CzechRepublic":"East",
	"Hungary":"East",
	"Poland":"East",
	"Moldova":"East",
	"Romania":"East",
	"Russia":"East",
	"Slovakia":"East",
	"Ukraine":"East",
	"AlandIslands":"North",
	"Denmark":"North",
	"Estonia":"North",
	"FaroeIslands":"North",
	"Finland":"North",
	"Guernsey":"North",
	"Iceland":"North",
	"Ireland":"North",
	"IsleofMan":"North",
	"Jersey":"North",
	"Latvia":"North",
	"Lithuania":"North",
	"Norway":"North",
	"Sark":"North",
	"SvalbardandJanMayen":"North",
	"Sweden":"North",
	"UnitedKingdom":"North",
	"Albania":"South",
	"Andorra":"South",
	"BosniaandHerzegovina":"South",
	"Croatia":"South",
	"Gibraltar":"South",
	"Greece":"South",
	"Italy":"South",
	"RepublicofMacedonia":"South",
	"Malta":"South",
	"Montenegro":"South",
	"Portugal":"South",
	"SanMarino":"South",
	"Serbia":"South",
	"Slovenia":"South",
	"Spain":"South",
	"VaticanCity":"South",
	"Austria":"West",
	"Belgium":"West",
	"France":"West",
	"Germany":"West",
	"Liechtenstein":"West",
	"Luxembourg":"West",
	"Monaco":"West",
	"Netherlands":"West",
	"Switzerland":"West",
}

var world_regions = {
	"Bangladesh":"Asia",
	"Bhutan":"Asia",
	"Brunei":"Asia",
	"Cambodia":"Asia",
	"China":"Asia",
	"India":"Asia",
	"Indonesia":"Asia",
	"Japan":"Asia",
	"Kazakhstan":"Asia",
	"North Korea":"Asia",
	"South Korea":"Asia",
	"Kyrgyzstan":"Asia",
	"Laos":"Asia",
	"Malaysia":"Asia",
	"Maldives":"Asia",
	"Mongolia":"Asia",
	"Myanmar":"Asia",
	"Nepal":"Asia",
	"Philippines":"Asia",
	"Singapore":"Asia",
	"Sri Lanka":"Asia",
	"Taiwan":"Asia",
	"Tajikistan":"Asia",
	"Thailand":"Asia",
	"Turkmenistan":"Asia",
	"Uzbekistan":"Asia",
	"Vietnam":"Asia",
	"Albania":"Europe",
	"Andorra":"Europe",
	"Armenia":"Europe",
	"Austria":"Europe",
	"Belarus":"Europe",
	"Belgium":"Europe",
	"Bosnia and Herzegovina":"Europe",
	"Bulgaria":"Europe",
	"Croatia":"Europe",
	"Cyprus":"Europe",
	"Czech Republic":"Europe",
	"Denmark":"Europe",
	"Estonia":"Europe",
	"Finland":"Europe",
	"France":"Europe",
	"Georgia":"Europe",
	"Germany":"Europe",
	"Greece":"Europe",
	"Hungary":"Europe",
	"Iceland*":"Europe",
	"Ireland":"Europe",
	"Italy":"Europe",
	"Kosovo":"Europe",
	"Latvia":"Europe",
	"Liechtenstein":"Europe",
	"Lithuania":"Europe",
	"Luxembourg":"Europe",
	"Macedonia":"Europe",
	"Malta":"Europe",
	"Moldova":"Europe",
	"Monaco":"Europe",
	"Montenegro":"Europe",
	"Netherlands":"Europe",
	"Norway":"Europe",
	"Poland":"Europe",
	"Portugal":"Europe",
	"Romania":"Europe",
	"Russia":"Europe",
	"San Marino":"Europe",
	"Serbia":"Europe",
	"Slovakia":"Europe",
	"Slovenia":"Europe",
	"Spain":"Europe",
	"Sweden":"Europe",
	"Switzerland":"Europe",
	"Ukraine":"Europe",
	"United Kingdom":"Europe",
	"Vatican City":"Europe",
	"Canada":"North America",
	"Greenland":"North America",
	"Mexico":"North America",
	"The United States of America":"North America",
	"Antigua and Barbuda":"Central America",
	"The Bahamas":"Central America",
	"Barbados":"Central America",
	"Belize":"Central America",
	"Costa Rica":"Central America",
	"Cuba":"Central America",
	"Dominica":"Central America",
	"Dominican Republic":"Central America",
	"El Salvador":"Central America",
	"Grenada":"Central America",
	"Guatemala":"Central America",
	"Haiti":"Central America",
	"Honduras":"Central America",
	"Jamaica":"Central America",
	"Nicaragua":"Central America",
	"Panama":"Central America",
	"Saint Kitts and Nevis":"Central America",
	"Saint Lucia":"Central America",
	"Saint Vincent and the Grenadines":"Central America",
	"Trinidad and Tobago":"Central America",
	"Argentina":"South America",
	"Bolivia":"South America",
	"Brazil":"South America",
	"Chile":"South America",
	"Colombia":"South America",
	"Ecuador":"South America",
	"Guyana":"South America",
	"Paraguay":"South America",
	"Peru":"South America",
	"Suriname":"South America",
	"Uruguay":"South America",
	"Venezuela":"South America",
	"Angola":"Africa",
	"Benin":"Africa",
	"Botswana":"Africa",
	"Burkina Faso":"Africa",
	"Burundi":"Africa",
	"Cameroon":"Africa",
	"Cape Verde":"Africa",
	"The Central African Republic":"Africa",
	"Chad":"Africa",
	"Comoros":"Africa",
	"Republic of the Congo":"Africa",
	"The Democratic Republic of the Congo":"Africa",
	"Cote d'Ivoire":"Africa",
	"Djibouti":"Africa",
	"Equatorial Guinea":"Africa",
	"Eritrea":"Africa",
	"Ethiopia":"Africa",
	"Gabon":"Africa",
	"The Gambia":"Africa",
	"Ghana":"Africa",
	"Guinea":"Africa",
	"Guinea-Bissau":"Africa",
	"Kenya":"Africa",
	"Lesotho":"Africa",
	"Liberia":"Africa",
	"Madagascar":"Africa",
	"Malawi":"Africa",
	"Mali":"Africa",
	"Mauritania":"Africa",
	"Mauritius":"Africa",
	"Mozambique":"Africa",
	"Namibia":"Africa",
	"Niger":"Africa",
	"Nigeria":"Africa",
	"Rwanda":"Africa",
	"Sao Tome and Principe":"Africa",
	"Senegal":"Africa",
	"Seychelles":"Africa",
	"Sierra Leone":"Africa",
	"South Africa":"Africa",
	"South Sudan":"Africa",
	"Sudan":"Africa",
	"Swaziland":"Africa",
	"Tanzania":"Africa",
	"Togo":"Africa",
	"Uganda":"Africa",
	"Zambia":"Africa",
	"Zimbabwe":"Africa",
	"Cyprus":"Middle East",
	"Egypt":"Middle East",
	"Iran":"Middle East",
	"Iraq":"Middle East",
	"Israel":"Middle East",
	"Jordan":"Middle East",
	"Kuwait":"Middle East",
	"Lebanon":"Middle East",
	"Oman":"Middle East",
	"Qatar":"Middle East",
	"Bahrain":"Middle East",
	"Saudi Arabia":"Middle East",
	"Syria":"Middle East",
	"Turkey":"Middle East",
	"United Arab Emirates":"Middle East",
	"Yemen":"Middle East"
}

