var usa_regions = {	
	"Alaska":"West", 
	"Alabama":"South", 
	"Arkansas":"South", 
	"Arizona":"West", 
	"California":"West", 
	"Colorado":"West", 
	"Connecticut":"Northeast", 
	"District of Columbia":"South", 
	"Delaware":"South", 
	"Florida":"South", 
	"Georgia":"South", 
	"Hawaii":"West", 
	"Iowa":"Midwest", 
	"Idaho":"West", 
	"Illinois":"Midwest", 
	"Indiana":"Midwest", 
	"Kansas":"Midwest", 
	"Kentucky":"South", 
	"Louisiana":"South", 
	"Massachusetts":"Northeast", 
	"Maryland":"South", 
	"Maine":"Northeast", 
	"Michigan":"Midwest", 
	"Minnesota":"Midwest", 
	"Missouri":"Midwest", 
	"Mississippi":"South", 
	"Montana":"West", 
	"North Carolina":"South", 
	"North Dakota":"Midwest", 
	"Nebraska":"Midwest", 
	"New Hampshire":"Northeast", 
	"New Jersey":"Northeast", 
	"New Mexico":"West", 
	"Nevada":"West", 
	"New York":"Northeast", 
	"Ohio":"Midwest", 
	"Oklahoma":"South", 
	"Oregon":"West", 
	"Pennsylvania":"Northeast", 
	"Rhode Island":"Northeast", 
	"South Carolina":"South", 
	"South Dakota":"Midwest", 
	"Tennessee":"South", 
	"Texas":"South", 
	"Utah":"West", 
	"Virginia":"South", 
	"Vermont":"Northeast", 
	"Washington":"West", 
	"Wisconsin":"Midwest", 
	"West Virginia":"South", 
	"Wyoming":"West"
}

var europe_regions = {
	"Belarus":"East",
	"Bulgaria":"East",
	"CzechRepublic":"East",
	"Hungary":"East",
	"Poland":"East",
	"Moldova":"East",
	"Romania":"East",
	"Russia":"East",
	"Slovakia":"East",
	"Ukraine":"East",
	"AlandIslands":"North",
	"Denmark":"North",
	"Estonia":"North",
	"FaroeIslands":"North",
	"Finland":"North",
	"Guernsey":"North",
	"Iceland":"North",
	"Ireland":"North",
	"IsleofMan":"North",
	"Jersey":"North",
	"Latvia":"North",
	"Lithuania":"North",
	"Norway":"North",
	"Sark":"North",
	"SvalbardandJanMayen":"North",
	"Sweden":"North",
	"UnitedKingdom":"North",
	"Albania":"South",
	"Andorra":"South",
	"BosniaandHerzegovina":"South",
	"Croatia":"South",
	"Gibraltar":"South",
	"Greece":"South",
	"Italy":"South",
	"RepublicofMacedonia":"South",
	"Malta":"South",
	"Montenegro":"South",
	"Portugal":"South",
	"SanMarino":"South",
	"Serbia":"South",
	"Slovenia":"South",
	"Spain":"South",
	"VaticanCity":"South",
	"Austria":"West",
	"Belgium":"West",
	"France":"West",
	"Germany":"West",
	"Liechtenstein":"West",
	"Luxembourg":"West",
	"Monaco":"West",
	"Netherlands":"West",
	"Switzerland":"West",
}
